/* Copyright 2026 Elian Schock, Jonas Schwenk */
export type SubmissionStatus = "new" | "ready" | "in-review";

export interface Submission {
  id: string;
  student: string;
  klasse: string;
  subject: string;
  assignment: string;
  submittedAt: string;
  aiConfidence: number;
  aiGrade: string;
  aiGradeNum: number;
  status: SubmissionStatus;
  flagged?: boolean;
  pages: number;
  rubricHits: number;
  rubricTotal: number;
}

const SUBMISSIONS: Submission[] = [
  {
    id: "9b-q5-anna",
    student: "Anna Bauer",
    klasse: "9b",
    subject: "Mathe",
    assignment: "Aufgabe 5 — Quadratische Gleichungen",
    submittedAt: "vor 2 Std.",
    aiConfidence: 92,
    aiGrade: "1,7",
    aiGradeNum: 1.7,
    status: "ready",
    pages: 3,
    rubricHits: 9,
    rubricTotal: 10,
  },
  {
    id: "9b-q5-ben",
    student: "Ben Schulz",
    klasse: "9b",
    subject: "Mathe",
    assignment: "Aufgabe 5 — Quadratische Gleichungen",
    submittedAt: "vor 4 Std.",
    aiConfidence: 88,
    aiGrade: "2,0",
    aiGradeNum: 2.0,
    status: "ready",
    pages: 3,
    rubricHits: 8,
    rubricTotal: 10,
  },
  {
    id: "9b-q5-cara",
    student: "Cara Lange",
    klasse: "9b",
    subject: "Mathe",
    assignment: "Aufgabe 5 — Quadratische Gleichungen",
    submittedAt: "gestern",
    aiConfidence: 41,
    aiGrade: "3,3",
    aiGradeNum: 3.3,
    status: "new",
    flagged: true,
    pages: 4,
    rubricHits: 5,
    rubricTotal: 10,
  },
  {
    id: "9b-q5-greta",
    student: "Greta Hoffmann",
    klasse: "9b",
    subject: "Mathe",
    assignment: "Aufgabe 5 — Quadratische Gleichungen",
    submittedAt: "vor 6 Std.",
    aiConfidence: 95,
    aiGrade: "2,2",
    aiGradeNum: 2.2,
    status: "ready",
    pages: 3,
    rubricHits: 8,
    rubricTotal: 10,
  },
  {
    id: "9b-q5-hannes",
    student: "Hannes Müller",
    klasse: "9b",
    subject: "Mathe",
    assignment: "Aufgabe 5 — Quadratische Gleichungen",
    submittedAt: "vor 8 Std.",
    aiConfidence: 84,
    aiGrade: "2,5",
    aiGradeNum: 2.5,
    status: "ready",
    pages: 3,
    rubricHits: 7,
    rubricTotal: 10,
  },
  {
    id: "9b-q5-lisa",
    student: "Lisa Hofer",
    klasse: "9b",
    subject: "Mathe",
    assignment: "Aufgabe 5 — Quadratische Gleichungen",
    submittedAt: "vor 1 Tag",
    aiConfidence: 71,
    aiGrade: "4,1",
    aiGradeNum: 4.1,
    status: "in-review",
    pages: 2,
    rubricHits: 3,
    rubricTotal: 10,
  },
  {
    id: "9b-q5-marlon",
    student: "Marlon Frey",
    klasse: "9b",
    subject: "Mathe",
    assignment: "Aufgabe 5 — Quadratische Gleichungen",
    submittedAt: "vor 1 Tag",
    aiConfidence: 78,
    aiGrade: "3,8",
    aiGradeNum: 3.8,
    status: "new",
    pages: 2,
    rubricHits: 4,
    rubricTotal: 10,
  },
  {
    id: "9b-q5-eva",
    student: "Eva Klein",
    klasse: "9b",
    subject: "Mathe",
    assignment: "Aufgabe 5 — Quadratische Gleichungen",
    submittedAt: "vor 5 Std.",
    aiConfidence: 89,
    aiGrade: "2,7",
    aiGradeNum: 2.7,
    status: "ready",
    pages: 3,
    rubricHits: 7,
    rubricTotal: 10,
  },
  {
    id: "9b-q5-felix",
    student: "Felix Wagner",
    klasse: "9b",
    subject: "Mathe",
    assignment: "Aufgabe 5 — Quadratische Gleichungen",
    submittedAt: "vor 3 Std.",
    aiConfidence: 86,
    aiGrade: "3,1",
    aiGradeNum: 3.1,
    status: "new",
    pages: 3,
    rubricHits: 6,
    rubricTotal: 10,
  },
  {
    id: "10a-hebel-david",
    student: "David Roth",
    klasse: "10a",
    subject: "Physik",
    assignment: "Versuchsprotokoll Hebelgesetz",
    submittedAt: "vor 1 Tag",
    aiConfidence: 78,
    aiGrade: "2,6",
    aiGradeNum: 2.6,
    status: "new",
    pages: 5,
    rubricHits: 11,
    rubricTotal: 14,
  },
  {
    id: "10a-hebel-eva",
    student: "Eva Klein",
    klasse: "10a",
    subject: "Physik",
    assignment: "Versuchsprotokoll Hebelgesetz",
    submittedAt: "vor 1 Tag",
    aiConfidence: 95,
    aiGrade: "2,9",
    aiGradeNum: 2.9,
    status: "ready",
    pages: 4,
    rubricHits: 10,
    rubricTotal: 14,
  },
  {
    id: "10a-hebel-aron",
    student: "Aron Berger",
    klasse: "10a",
    subject: "Physik",
    assignment: "Versuchsprotokoll Hebelgesetz",
    submittedAt: "vor 1 Tag",
    aiConfidence: 91,
    aiGrade: "1,9",
    aiGradeNum: 1.9,
    status: "ready",
    pages: 5,
    rubricHits: 13,
    rubricTotal: 14,
  },
  {
    id: "10a-hebel-clara",
    student: "Clara Sommer",
    klasse: "10a",
    subject: "Physik",
    assignment: "Versuchsprotokoll Hebelgesetz",
    submittedAt: "vor 2 Tagen",
    aiConfidence: 87,
    aiGrade: "2,2",
    aiGradeNum: 2.2,
    status: "ready",
    pages: 4,
    rubricHits: 12,
    rubricTotal: 14,
  },
  {
    id: "10a-hebel-henrik",
    student: "Henrik Solter",
    klasse: "10a",
    subject: "Physik",
    assignment: "Versuchsprotokoll Hebelgesetz",
    submittedAt: "vor 1 Tag",
    aiConfidence: 82,
    aiGrade: "3,3",
    aiGradeNum: 3.3,
    status: "ready",
    pages: 4,
    rubricHits: 9,
    rubricTotal: 14,
  },
  {
    id: "10a-hebel-mira",
    student: "Mira Salim",
    klasse: "10a",
    subject: "Physik",
    assignment: "Versuchsprotokoll Hebelgesetz",
    submittedAt: "vor 2 Tagen",
    aiConfidence: 73,
    aiGrade: "3,9",
    aiGradeNum: 3.9,
    status: "new",
    pages: 3,
    rubricHits: 7,
    rubricTotal: 14,
  },
  {
    id: "10a-hebel-paul",
    student: "Paul Engel",
    klasse: "10a",
    subject: "Physik",
    assignment: "Versuchsprotokoll Hebelgesetz",
    submittedAt: "vor 3 Tagen",
    aiConfidence: 68,
    aiGrade: "4,3",
    aiGradeNum: 4.3,
    status: "new",
    pages: 3,
    rubricHits: 5,
    rubricTotal: 14,
  },
  {
    id: "10a-mech-tom",
    student: "Tom Weber",
    klasse: "10a",
    subject: "Physik",
    assignment: "Online-Test Mechanik",
    submittedAt: "vor 2 Std.",
    aiConfidence: 99,
    aiGrade: "4,2",
    aiGradeNum: 4.2,
    status: "ready",
    pages: 1,
    rubricHits: 8,
    rubricTotal: 20,
  },
  {
    id: "10a-mech-jonas",
    student: "Jonas Frank",
    klasse: "10a",
    subject: "Physik",
    assignment: "Online-Test Mechanik",
    submittedAt: "vor 4 Std.",
    aiConfidence: 99,
    aiGrade: "3,6",
    aiGradeNum: 3.6,
    status: "ready",
    pages: 1,
    rubricHits: 11,
    rubricTotal: 20,
  },
  {
    id: "10a-mech-gisela",
    student: "Gisela Maus",
    klasse: "10a",
    subject: "Physik",
    assignment: "Online-Test Mechanik",
    submittedAt: "vor 6 Std.",
    aiConfidence: 99,
    aiGrade: "2,7",
    aiGradeNum: 2.7,
    status: "ready",
    pages: 1,
    rubricHits: 15,
    rubricTotal: 20,
  },
  {
    id: "8c-bruch-amir",
    student: "Amir Köster",
    klasse: "8c",
    subject: "Mathe",
    assignment: "Bruchrechnen — Wochenübung",
    submittedAt: "vor 30 Min.",
    aiConfidence: 96,
    aiGrade: "1,4",
    aiGradeNum: 1.4,
    status: "ready",
    pages: 2,
    rubricHits: 9,
    rubricTotal: 10,
  },
  {
    id: "8c-bruch-bea",
    student: "Bea Hertz",
    klasse: "8c",
    subject: "Mathe",
    assignment: "Bruchrechnen — Wochenübung",
    submittedAt: "vor 1 Std.",
    aiConfidence: 94,
    aiGrade: "1,7",
    aiGradeNum: 1.7,
    status: "ready",
    pages: 2,
    rubricHits: 9,
    rubricTotal: 10,
  },
  {
    id: "8c-bruch-mira",
    student: "Mira Sandt",
    klasse: "8c",
    subject: "Mathe",
    assignment: "Bruchrechnen — Wochenübung",
    submittedAt: "vor 3 Std.",
    aiConfidence: 80,
    aiGrade: "3,8",
    aiGradeNum: 3.8,
    status: "in-review",
    pages: 2,
    rubricHits: 4,
    rubricTotal: 10,
  },
  {
    id: "11a-feder-dennis",
    student: "Dennis Mahr",
    klasse: "11a",
    subject: "Physik",
    assignment: "Versuchsprotokoll Federpendel",
    submittedAt: "vor 5 Std.",
    aiConfidence: 76,
    aiGrade: "3,1",
    aiGradeNum: 3.1,
    status: "new",
    pages: 4,
    rubricHits: 8,
    rubricTotal: 14,
  },
];

export const KORREKTUR_STATS = {
  todayGraded: 12,
  totalOpen: SUBMISSIONS.length,
  avgConfidence: Math.round(
    SUBMISSIONS.reduce((s, x) => s + x.aiConfidence, 0) / SUBMISSIONS.length
  ),
  timeSavedHours: 11.4,
  autoReady: SUBMISSIONS.filter((s) => s.status === "ready").length,
};

export const KORREKTUR_KLASSEN = ["9b", "10a", "8c", "11a"] as const;

export const STATUS_FILTERS: { value: SubmissionStatus | "all"; label: string }[] = [
  { value: "all", label: "Alle" },
  { value: "ready", label: "KI-bereit" },
  { value: "new", label: "Neu" },
  { value: "in-review", label: "In Prüfung" },
];

export function listSubmissions(): Submission[] {
  return SUBMISSIONS;
}
