/* Copyright 2026 Elian Schock, Jonas Schwenk */
// Dokument-Vorlagen für den Word-Editor.
// content ist ein HTML-String (gleiches Format wie DocumentEditor speichert).

export type DocumentTemplate = {
  key: string;
  name: string;
  emoji: string;
  description: string;
  title: string;
  content: string;
};

export const DOCUMENT_TEMPLATES: readonly DocumentTemplate[] = [
  {
    key: "brief-formell",
    name: "Formeller Brief",
    emoji: "✉️",
    description: "Klassischer Geschäftsbrief mit Absender, Empfänger und Grußformel.",
    title: "Formeller Brief",
    content: [
      "<p>[Dein Vorname Nachname]<br>[Straße Hausnummer]<br>[PLZ Ort]</p>",
      "<p><br></p>",
      "<p>[Name des Empfängers]<br>[Firma / Institution]<br>[Straße Hausnummer]<br>[PLZ Ort]</p>",
      "<p><br></p>",
      "<p style=\"text-align: right;\">[Ort], den [Datum]</p>",
      "<p><br></p>",
      "<p><b>Betreff: [Worum geht es?]</b></p>",
      "<p><br></p>",
      "<p>Sehr geehrte Damen und Herren,</p>",
      "<p>[Einleitung: Warum schreibst du diesen Brief?]</p>",
      "<p>[Hauptteil: Erläutere dein Anliegen sachlich und klar.]</p>",
      "<p>[Schluss: Was erwartest du als Antwort oder nächsten Schritt?]</p>",
      "<p><br></p>",
      "<p>Mit freundlichen Grüßen</p>",
      "<p>[Dein Vorname Nachname]</p>",
    ].join(""),
  },
  {
    key: "lebenslauf",
    name: "Lebenslauf",
    emoji: "📄",
    description: "Tabellarischer Lebenslauf für Bewerbung oder Praktikum.",
    title: "Lebenslauf",
    content: [
      "<h1>Lebenslauf</h1>",
      "<h2>Persönliche Daten</h2>",
      "<table border=\"1\" style=\"width: 100%; border-collapse: collapse;\">",
      "<tr><td style=\"padding: 6px; width: 35%;\"><b>Name</b></td><td style=\"padding: 6px;\">[Vorname Nachname]</td></tr>",
      "<tr><td style=\"padding: 6px;\"><b>Geburtsdatum</b></td><td style=\"padding: 6px;\">[TT.MM.JJJJ] in [Geburtsort]</td></tr>",
      "<tr><td style=\"padding: 6px;\"><b>Anschrift</b></td><td style=\"padding: 6px;\">[Straße Hausnummer, PLZ Ort]</td></tr>",
      "<tr><td style=\"padding: 6px;\"><b>E-Mail / Telefon</b></td><td style=\"padding: 6px;\">[E-Mail-Adresse] · [Telefonnummer]</td></tr>",
      "</table>",
      "<h2>Schulbildung</h2>",
      "<table border=\"1\" style=\"width: 100%; border-collapse: collapse;\">",
      "<tr><td style=\"padding: 6px; width: 35%;\">[Jahr – Jahr]</td><td style=\"padding: 6px;\">[Name der Schule, Ort]</td></tr>",
      "<tr><td style=\"padding: 6px;\">[Jahr – heute]</td><td style=\"padding: 6px;\">[Aktuelle Schule, angestrebter Abschluss]</td></tr>",
      "</table>",
      "<h2>Praktische Erfahrungen</h2>",
      "<table border=\"1\" style=\"width: 100%; border-collapse: collapse;\">",
      "<tr><td style=\"padding: 6px; width: 35%;\">[Zeitraum]</td><td style=\"padding: 6px;\">[Praktikum / Nebenjob, Firma, Ort]</td></tr>",
      "</table>",
      "<h2>Kenntnisse und Interessen</h2>",
      "<ul><li>Sprachen: [z. B. Deutsch (Muttersprache), Englisch (gut)]</li><li>EDV: [z. B. Word, Excel, Programmieren]</li><li>Hobbys: [z. B. Fußball, Lesen, Musik]</li></ul>",
      "<p><br></p>",
      "<p>[Ort], den [Datum]</p>",
      "<p>[Unterschrift]</p>",
    ].join(""),
  },
  {
    key: "referat-gliederung",
    name: "Referat-Gliederung",
    emoji: "🎤",
    description: "Strukturierte Gliederung für dein nächstes Referat.",
    title: "Referat: [Thema]",
    content: [
      "<h1>Referat: [Thema]</h1>",
      "<p><b>Fach:</b> [Fach] · <b>Name:</b> [Dein Name] · <b>Datum:</b> [Datum]</p>",
      "<h2>1. Einleitung</h2>",
      "<ul><li>[Einstieg: Frage, Zitat oder überraschende Zahl]</li><li>[Warum ist das Thema wichtig?]</li><li>[Überblick über den Aufbau]</li></ul>",
      "<h2>2. Hauptteil</h2>",
      "<h2>2.1 [Erster Unterpunkt]</h2>",
      "<ul><li>[Wichtige Fakten und Erklärungen]</li><li>[Beispiel]</li></ul>",
      "<h2>2.2 [Zweiter Unterpunkt]</h2>",
      "<ul><li>[Wichtige Fakten und Erklärungen]</li><li>[Beispiel]</li></ul>",
      "<h2>2.3 [Dritter Unterpunkt]</h2>",
      "<ul><li>[Wichtige Fakten und Erklärungen]</li></ul>",
      "<h2>3. Schluss</h2>",
      "<ul><li>[Zusammenfassung der wichtigsten Punkte]</li><li>[Eigene Meinung / Fazit]</li><li>[Offene Frage an das Publikum]</li></ul>",
      "<h2>Quellen</h2>",
      "<ul><li>[Quelle 1: Buch, Website oder Artikel]</li><li>[Quelle 2]</li></ul>",
    ].join(""),
  },
  {
    key: "praktikumsbericht",
    name: "Praktikumsbericht",
    emoji: "🏢",
    description: "Vollständiger Aufbau für deinen Bericht zum Schülerpraktikum.",
    title: "Praktikumsbericht",
    content: [
      "<h1>Praktikumsbericht</h1>",
      "<p><b>Name:</b> [Dein Name] · <b>Klasse:</b> [Klasse] · <b>Zeitraum:</b> [von – bis]</p>",
      "<p><b>Betrieb:</b> [Name des Betriebs, Ort] · <b>Betreuer/in:</b> [Name]</p>",
      "<h2>1. Der Betrieb</h2>",
      "<p>[Beschreibe den Betrieb: Branche, Größe, Standort, Aufgaben des Betriebs.]</p>",
      "<h2>2. Erwartungen an das Praktikum</h2>",
      "<p>[Was hast du dir vor dem Praktikum vorgenommen und erhofft?]</p>",
      "<h2>3. Mein Arbeitsalltag</h2>",
      "<p>[Beschreibe einen typischen Tag: Arbeitszeiten, Aufgaben, Abläufe.]</p>",
      "<h2>4. Eine besondere Aufgabe</h2>",
      "<p>[Beschreibe eine Aufgabe genauer: Was hast du gemacht? Was hast du dabei gelernt?]</p>",
      "<h2>5. Fazit</h2>",
      "<p>[Wurden deine Erwartungen erfüllt? Könntest du dir diesen Beruf vorstellen? Warum (nicht)?]</p>",
    ].join(""),
  },
  {
    key: "protokoll",
    name: "Protokoll",
    emoji: "📝",
    description: "Ergebnisprotokoll für Unterricht, AG oder Klassenrat.",
    title: "Protokoll vom [Datum]",
    content: [
      "<h1>Protokoll</h1>",
      "<table border=\"1\" style=\"width: 100%; border-collapse: collapse;\">",
      "<tr><td style=\"padding: 6px; width: 35%;\"><b>Anlass</b></td><td style=\"padding: 6px;\">[z. B. Klassenrat, Gruppenarbeit, AG-Treffen]</td></tr>",
      "<tr><td style=\"padding: 6px;\"><b>Datum / Zeit</b></td><td style=\"padding: 6px;\">[Datum], [von – bis Uhr]</td></tr>",
      "<tr><td style=\"padding: 6px;\"><b>Ort</b></td><td style=\"padding: 6px;\">[Raum / Ort]</td></tr>",
      "<tr><td style=\"padding: 6px;\"><b>Anwesende</b></td><td style=\"padding: 6px;\">[Namen]</td></tr>",
      "<tr><td style=\"padding: 6px;\"><b>Protokollant/in</b></td><td style=\"padding: 6px;\">[Dein Name]</td></tr>",
      "</table>",
      "<h2>Tagesordnung</h2>",
      "<ol><li>[Punkt 1]</li><li>[Punkt 2]</li><li>[Punkt 3]</li></ol>",
      "<h2>Ergebnisse</h2>",
      "<p><b>Zu 1:</b> [Was wurde besprochen und beschlossen?]</p>",
      "<p><b>Zu 2:</b> [Was wurde besprochen und beschlossen?]</p>",
      "<p><b>Zu 3:</b> [Was wurde besprochen und beschlossen?]</p>",
      "<h2>Aufgaben bis zum nächsten Treffen</h2>",
      "<ul><li>[Aufgabe] – [zuständige Person] – bis [Datum]</li><li>[Aufgabe] – [zuständige Person] – bis [Datum]</li></ul>",
    ].join(""),
  },
  {
    key: "bewerbung",
    name: "Bewerbungsschreiben",
    emoji: "💼",
    description: "Anschreiben für Praktikum oder Ausbildungsplatz.",
    title: "Bewerbung um [Stelle]",
    content: [
      "<p>[Dein Vorname Nachname]<br>[Straße Hausnummer]<br>[PLZ Ort]<br>[E-Mail-Adresse] · [Telefonnummer]</p>",
      "<p><br></p>",
      "<p>[Firma]<br>[Ansprechpartner/in]<br>[Straße Hausnummer]<br>[PLZ Ort]</p>",
      "<p><br></p>",
      "<p style=\"text-align: right;\">[Ort], den [Datum]</p>",
      "<p><br></p>",
      "<p><b>Bewerbung um [einen Praktikumsplatz / einen Ausbildungsplatz als …]</b></p>",
      "<p><br></p>",
      "<p>Sehr geehrte/r [Frau/Herr Nachname],</p>",
      "<p>[Einleitung: Wie bist du auf die Stelle aufmerksam geworden? Warum bewirbst du dich genau hier?]</p>",
      "<p>[Hauptteil: Wer bist du (Schule, Klasse)? Welche Stärken, Interessen und Erfahrungen bringst du mit, die zur Stelle passen?]</p>",
      "<p>[Schluss: Verfügbarer Zeitraum, Freude über eine Einladung zum Gespräch.]</p>",
      "<p><br></p>",
      "<p>Mit freundlichen Grüßen</p>",
      "<p>[Dein Vorname Nachname]</p>",
      "<p><br></p>",
      "<p><b>Anlagen:</b> Lebenslauf, letztes Zeugnis</p>",
    ].join(""),
  },
  {
    key: "handout",
    name: "Handout",
    emoji: "📋",
    description: "Kompaktes Handout zum Austeilen bei deinem Referat.",
    title: "Handout: [Thema]",
    content: [
      "<h1>Handout: [Thema]</h1>",
      "<p>[Dein Name] · [Fach] · [Klasse] · [Datum]</p>",
      "<h2>Das Wichtigste in Kürze</h2>",
      "<p>[Zwei bis drei Sätze, die das Thema zusammenfassen.]</p>",
      "<h2>Kernpunkte</h2>",
      "<ul><li><b>[Stichwort 1]:</b> [kurze Erklärung]</li><li><b>[Stichwort 2]:</b> [kurze Erklärung]</li><li><b>[Stichwort 3]:</b> [kurze Erklärung]</li></ul>",
      "<h2>Wichtige Begriffe</h2>",
      "<table border=\"1\" style=\"width: 100%; border-collapse: collapse;\">",
      "<tr><td style=\"padding: 6px; width: 35%;\"><b>[Begriff]</b></td><td style=\"padding: 6px;\">[Definition]</td></tr>",
      "<tr><td style=\"padding: 6px;\"><b>[Begriff]</b></td><td style=\"padding: 6px;\">[Definition]</td></tr>",
      "</table>",
      "<h2>Merksatz</h2>",
      "<p><b>[Ein Satz, den sich alle merken sollen.]</b></p>",
      "<h2>Quellen</h2>",
      "<ul><li>[Quelle 1]</li><li>[Quelle 2]</li></ul>",
    ].join(""),
  },
  {
    key: "todo-checkliste",
    name: "To-do-Checkliste",
    emoji: "✅",
    description: "Checkliste für Hausaufgaben, Projekte oder die Klassenarbeit.",
    title: "To-do-Liste",
    content: [
      "<h1>To-do-Liste: [Woche / Projekt]</h1>",
      "<p><b>Stand:</b> [Datum]</p>",
      "<h2>Dringend (heute)</h2>",
      "<ul><li>☐ [Aufgabe 1]</li><li>☐ [Aufgabe 2]</li></ul>",
      "<h2>Diese Woche</h2>",
      "<ul><li>☐ [Aufgabe] – bis [Wochentag]</li><li>☐ [Aufgabe] – bis [Wochentag]</li><li>☐ [Aufgabe] – bis [Wochentag]</li></ul>",
      "<h2>Später / Ideen</h2>",
      "<ul><li>☐ [Aufgabe oder Idee]</li><li>☐ [Aufgabe oder Idee]</li></ul>",
      "<h2>Erledigt</h2>",
      "<ul><li>☑ [Fertige Aufgabe hier eintragen]</li></ul>",
      "<p><i>Tipp: Ersetze ☐ durch ☑, wenn eine Aufgabe erledigt ist.</i></p>",
    ].join(""),
  },
];

export function getDocumentTemplate(key: string): DocumentTemplate | undefined {
  return DOCUMENT_TEMPLATES.find((t) => t.key === key);
}
